animations {
    enabled = true

    # Curve di Bezier per movimento inerziale
    # "fluid" simula un oggetto con massa che scivola e rallenta
    bezier = fluid, 0.22, 1, 0.36, 1
    # "glitchy" per un feedback istantaneo e secco
    bezier = snap, 0.05, 0.9, 0.1, 1

    # FINESTRE: Effetto Slide Laterale
    # Quando apri una finestra nel nastro, deve "entrare" lateralmente
    animation = windowsIn, 1, 5, fluid, slide
    animation = windowsOut, 1, 5, fluid, slide

    # Questo è il cuore dello scrolling: il movimento delle finestre esistenti
    # che si spostano per fare spazio alla nuova. Deve essere burroso.
    animation = windowsMove, 1, 6, fluid

    # WORKSPACES: Nastro continuo
    # Usiamo 'slidefade' per un passaggio fluido tra i set di finestre
    animation = workspaces, 1, 6, fluid, slidefade 20%

    # BORDI E DECORAZIONI
    animation = border, 1, 10, default
    animation = borderangle, 1, 100, snap, loop
    animation = fadeIn, 1, 4, snap
}
