
$background = rgba(151407ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(323121ff)

$inverse_primary = rgba(666000ff)

$inverse_surface = rgba(e8e3ccff)

$on_background = rgba(e8e3ccff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(353200ff)

$on_primary_container = rgba(f3e700ff)

$on_primary_fixed = rgba(1e1c00ff)

$on_primary_fixed_variant = rgba(4d4800ff)

$on_secondary = rgba(2e330dff)

$on_secondary_container = rgba(e0e7b1ff)

$on_secondary_fixed = rgba(191e00ff)

$on_secondary_fixed_variant = rgba(444a22ff)

$on_surface = rgba(e8e3ccff)

$on_surface_variant = rgba(cbc7b1ff)

$on_tertiary = rgba(213608ff)

$on_tertiary_container = rgba(d0ecabff)

$on_tertiary_fixed = rgba(0f2000ff)

$on_tertiary_fixed_variant = rgba(374d1dff)

$outline = rgba(94917dff)

$outline_variant = rgba(494736ff)

$primary = rgba(d5cb00ff)

$primary_container = rgba(4d4800ff)

$primary_fixed = rgba(f3e700ff)

$primary_fixed_dim = rgba(d5cb00ff)

$scrim = rgba(000000ff)

$secondary = rgba(c4cb97ff)

$secondary_container = rgba(444a22ff)

$secondary_fixed = rgba(e0e7b1ff)

$secondary_fixed_dim = rgba(c4cb97ff)

$shadow = rgba(000000ff)

$source_color = rgba(54512cff)

$surface = rgba(151407ff)

$surface_bright = rgba(3b3a2aff)

$surface_container = rgba(212012ff)

$surface_container_high = rgba(2c2a1bff)

$surface_container_highest = rgba(373525ff)

$surface_container_low = rgba(1d1c0eff)

$surface_container_lowest = rgba(100f04ff)

$surface_dim = rgba(151407ff)

$surface_tint = rgba(d5cb00ff)

$surface_variant = rgba(494736ff)

$tertiary = rgba(b4d091ff)

$tertiary_container = rgba(374d1dff)

$tertiary_fixed = rgba(d0ecabff)

$tertiary_fixed_dim = rgba(b4d091ff)

