
$background = rgba(131313ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303030ff)

$inverse_primary = rgba(9b404fff)

$inverse_surface = rgba(e2e2e2ff)

$on_background = rgba(e2e2e2ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(5f1223ff)

$on_primary_container = rgba(ffd9dcff)

$on_primary_fixed = rgba(400011ff)

$on_primary_fixed_variant = rgba(7d2938ff)

$on_secondary = rgba(43292cff)

$on_secondary_container = rgba(ffd9dcff)

$on_secondary_fixed = rgba(2c1518ff)

$on_secondary_fixed_variant = rgba(5c3f42ff)

$on_surface = rgba(e2e2e2ff)

$on_surface_variant = rgba(c6c6c6ff)

$on_tertiary = rgba(442b07ff)

$on_tertiary_container = rgba(ffddb7ff)

$on_tertiary_fixed = rgba(2a1700ff)

$on_tertiary_fixed_variant = rgba(5d411bff)

$outline = rgba(919191ff)

$outline_variant = rgba(474747ff)

$primary = rgba(ffb2baff)

$primary_container = rgba(7d2938ff)

$primary_fixed = rgba(ffd9dcff)

$primary_fixed_dim = rgba(ffb2baff)

$scrim = rgba(000000ff)

$secondary = rgba(e5bdc0ff)

$secondary_container = rgba(5c3f42ff)

$secondary_fixed = rgba(ffd9dcff)

$secondary_fixed_dim = rgba(e5bdc0ff)

$shadow = rgba(000000ff)

$source_color = rgba(b8284aff)

$surface = rgba(131313ff)

$surface_bright = rgba(393939ff)

$surface_container = rgba(1f1f1fff)

$surface_container_high = rgba(2a2a2aff)

$surface_container_highest = rgba(353535ff)

$surface_container_low = rgba(1b1b1bff)

$surface_container_lowest = rgba(0e0e0eff)

$surface_dim = rgba(131313ff)

$surface_tint = rgba(ffb2baff)

$surface_variant = rgba(474747ff)

$tertiary = rgba(e9bf8fff)

$tertiary_container = rgba(5d411bff)

$tertiary_fixed = rgba(ffddb7ff)

$tertiary_fixed_dim = rgba(e9bf8fff)

