palette = "gruvbox_rainbow"

format = """
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
[](fg:color_aqua bg:color_blue)\
$python\
[](fg:color_blue)\
$line_break$character"""

[palettes.gruvbox_rainbow]
color_fg0 = "#fbf1c7"
color_bg1 = "#3c3836"
color_bg3 = "#665c54"
color_green = "#b8bb26"
color_orange = "#d65d0e"
color_yellow = "#d79921"
color_aqua = "#003E50"
color_blue = "#458588"
color_purple = "#b16286"
color_red = "#cc241d"

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold color_green)'
error_symbol = '[❯](bold color_red)'
format = '$symbol '

[username]
show_always = true
style_user = 'bg:color_orange fg:color_fg0'
style_root = 'bg:color_orange fg:color_red'
format = '[ $user ]($style)'

[directory]
style = 'bg:color_yellow fg:color_bg1'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "📄 "
"Downloads" = "📥 "
"Music" = "🎵 "
"Pictures" = "🖼️ "
"Videos" = "🎬 "
"Desktop" = "🖥️ "
"Projects" = "📁 "
"~" = "🏠 "
"tmp" = "🗑️ "
"tests" = "🧪 "
"build" = "🔨 "
"node_modules" = "📦 "
".git" = "🔀 "
".github" = "🐙 "
"images" = "🖼️ "
"fonts" = "🔤 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ PICKING](bold red)'

[git_status]
style = 'bg:color_aqua fg:color_fg0'
format = '[ $all_status$ahead_behind]($style)'
modified = '[ +$count ](fg:color_yellow bg:color_aqua)'
untracked = '[ $count](fg:color_orange bg:color_aqua)'
deleted = '[ -$count](fg:color_red bg:color_aqua)'
staged = '[ ++$count](fg:color_green bg:color_aqua)'
conflicted = '[ $count](fg:color_red bg:color_aqua)'
stashed = '[ $count](fg:color_purple bg:color_aqua)'
renamed = '[ $count](fg:color_orange bg:color_aqua)'
ahead = '[  $count](fg:color_green bg:color_aqua)'
behind = '[  $count](fg:color_red bg:color_aqua)'
diverged = '[  ${ahead_count}  ${behind_count}](fg:color_orange bg:color_aqua)'

[git_metrics]
disabled = false
format = '[  ](fg:color_fg0 bg:color_aqua)[+$added](fg:color_green bg:color_aqua)[ -$deleted ](fg:color_red bg:color_aqua)'
added_style = ''
deleted_style = ''

[git_branch]
symbol = ' '
style = 'bg:color_aqua fg:color_fg0'
# format = '[ $symbol $branch ]($style)'
format = '[ $symbol$branch(:$remote_branch)]($style)'

[git_commit]
# format = '[$hash $tag ]($style)'
format = '[  $hash ]($style)'
commit_hash_length = 5
only_detached = false
tag_symbol = ' '
style = 'bg:color_aqua fg:color_blue'

[sudo]
style = 'bg:#2C3E50'
symbol = '👿 '
disabled = true

[python]
symbol = '🐍'
style = 'bg:color_blue fg:color_fg0'
format = '[ $symbol$pyenv_prefix($version)(\($virtualenv\)) ]($style)'
pyenv_version_name = false
