# Alacritty - TOML configuration file format.

# DESCRIPTION

general.import = ["~/.config/alacritty/theme.toml"]
general.live_config_reload = true
general.ipc_socket = true

#[terminal.shell]
#program = "/usr/bin/fish"
#args = ["-l"]

[env]
TERM = "xterm-256color"
# WINIT_X11_SCALE_FACTOR = "1.0"

# dynamic_padding = true | false
# Spread additional padding evenly around the terminal content.
# Default: false

[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 1
padding = { x = 10, y = 10 }
decorations = "Full"
dynamic_padding = false

[scrolling]
history = 20000
multiplier = 3


# FONT

# offset = { x = <integer>, y = <integer> }
# Offset is the extra space around each character. The 'y' can be thought of as modifying the line spacing, and 'x' as modifying the letter spacing.
# Default: { x = 0, y = 0 }

# glyph_offset = { x = <integer>, y = <integer> }
# Glyph offset determines the locations of the glyphs within their cells with the default being at the bottom. Increasing x moves the glyph to the right, increasing y moves the glyph upward.

# builtin_box_drawing = true | false
# When true, Alacritty will use a custom built-in font for box drawing characters (Unicode points U+2500 - U+259F) and powerline symbols (Unicode points U+E0B0 - U+E0B3).
# Default: true

[font]
size = 18
# normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
# bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
# italic = { family = "Fisa Code", style = "Italic" }
# bold_italic = { family = "Fisa Code", style = "Bold Italic" }

normal = { family = "PragmataProMonoLiga Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = {  style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
offset = { x = 0, y = 0 }
builtin_box_drawing = true



# SELECTION
[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true


# CURSOR
# This section documents the [cursor] table of the configuration file.

# style = { <shape>, <blinking> }

# shape = "Block" | "Underline" | "Beam"
# Default: "Block"

# blinking = "Never" | "Off" | "On" | "Always"
# Never - Prevent the cursor from ever blinking
# Off - Disable blinking by default
# On - Enable blinking by default
# Always -Force the cursor to always blink
# Default: "Off"

# vi_mode_style = { <shape>, <blinking> } | "None"
# If the vi mode cursor style is "None" or not specified, it will fall back to the active value of the normal cursor.
# Default: "None"

# blink_interval = <integer>
# Cursor blinking interval in milliseconds.
# Default: 750

# blink_timeout = <integer>
# Time after which cursor stops blinking, in seconds.
# Specifying 0 will disable timeout for blinking.
# Default: 5

# unfocused_hollow = true | false
# When this is true, the cursor will be rendered as a hollow box when the window is not focused.
# Default: true
# thickness = <float>
# Thickness of the cursor relative to the cell width as floating point number from 0.0 to 1.0.
# Default: 0.15

[cursor]
style = { shape = "Beam", blinking = "Always" }
unfocused_hollow = true
thickness = 0.15
blink_interval = 150
blink_timeout = 2




# TERMINAL
# This section documents the [terminal] table of the configuration file.
# osc52 = "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"
# Controls the ability to write to the system clipboard with the OSC 52 escape sequence. While this escape sequence is useful to copy contents from the remote server, allowing any application to read from the clipboard can be easily abused while not providing significant benefits over explicitly pasting text.
# Default: "OnlyCopy"

#[terminal]


# MOUSE

[mouse]
hide_when_typing = true

