# Material Dark Theme - Vivid and Readable
# Basato sui colori Material Design con alta leggibilità

[colors.primary]
background = '#0f111a'  # Background molto scuro blu-nero
foreground = '#eeffff'  # Foreground bianco brillante per massima leggibilità

[colors.cursor]
text = '#0f111a'
cursor = '#ffcc02'  # Cursore giallo vivido per alta visibilità

[colors.selection]
text = '#eeffff'
background = '#80cbc4'  # Selezione teal chiaro

[colors.normal]
black = '#000000'
red = '#f07178'      # Rosso Material vivido e leggibile
green = '#c3e88d'    # Verde Material brillante
yellow = '#ffcb6b'   # Giallo Material vivace
blue = '#82b1ff'     # Blu Material chiaro e brillante
magenta = '#c792ea'  # Magenta Material vivido
cyan = '#89ddff'     # Cyan Material luminoso
white = '#ffffff'    # Bianco puro

[colors.bright]
black = '#546e7a'    # Grigio Material
red = '#ff5370'      # Rosso più vivido
green = '#c3e88d'    # Verde mantenuto brillante
yellow = '#ffcb6b'   # Giallo mantenuto vivace
blue = '#82b1ff'     # Blu mantenuto brillante
magenta = '#c792ea'  # Magenta mantenuto vivido
cyan = '#89ddff'     # Cyan mantenuto luminoso  
white = '#ffffff'    # Bianco massima luminosità

# Colori aggiuntivi per migliorare la leggibilità
[[colors.indexed_colors]]
index = 16
color = '#f78c6c'  # Arancione Material

[[colors.indexed_colors]]
index = 17
color = '#ff5370'  # Rosso accento

[[colors.indexed_colors]]
index = 18
color = '#263238'  # Grigio scuro Material

[[colors.indexed_colors]]
index = 19
color = '#2e3c43'  # Grigio medio scuro

[[colors.indexed_colors]]
index = 20
color = '#314549'  # Grigio medio

[[colors.indexed_colors]]
index = 21
color = '#eeffff'  # Bianco off-white